[package]
name = "colony-assault"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", features = ["dynamic_linking"] }
bevy_rapier2d = "0.27.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
